import os
import shutil
import tempfile
import subprocess
from unittest.mock import patch, MagicMock
from worker.ffmpeg_worker import transcode_video


@patch("subprocess.run")
@patch("os.path.exists")
@patch("os.path.getsize")
def test_transcode_video_mocked(mock_getsize, mock_exists, mock_run):
    """
    Test that transcode_video calls subprocess.run with the correct FFmpeg commands
    and arguments, mocking file system and subprocess execution.
    """
    # 1. Setup mocks
    mock_exists.return_value = True
    mock_getsize.return_value = 1000

    # Mock subprocess.run return value
    mock_res = MagicMock()
    mock_res.returncode = 0
    mock_res.stdout = "Mock output"
    mock_res.stderr = ""
    mock_run.return_value = mock_res

    # 2. Run function
    result = transcode_video(
        input_path="dummy_input.mp4",
        output_dir="dummy_output",
        video_id="test_video_123"
    )

    assert result is True
    # The function should invoke mock_run for:
    # 1. version check (or more)
    # 2. 720p command
    # 3. 480p command
    # 4. thumbnail command
    assert mock_run.call_count >= 4

    # Extract all command lists passed to subprocess.run
    called_cmds = [call[0][0] for call in mock_run.call_args_list]

    # Verify that the 720p scaling filter is configured
    cmd_720p_found = False
    for cmd in called_cmds:
        if "scale=-2:720" in cmd:
            cmd_720p_found = True
            assert "ffmpeg" in cmd
            assert "-i" in cmd
            assert "libx264" in cmd
    assert cmd_720p_found

    # Verify that the 480p scaling filter is configured
    cmd_480p_found = False
    for cmd in called_cmds:
        if "scale=-2:480" in cmd:
            cmd_480p_found = True
            assert "ffmpeg" in cmd
            assert "-i" in cmd
            assert "libx264" in cmd
    assert cmd_480p_found

    # Verify that the thumbnail capture is configured
    cmd_thumb_found = False
    for cmd in called_cmds:
        if "00:00:05" in cmd or "5" in cmd:
            cmd_thumb_found = True
            assert "-vframes" in cmd or "-frames:v" in cmd
    assert cmd_thumb_found


def test_transcode_video_integration():
    """
    Integration test that runs the worker on a small, valid dummy video
    generated by FFmpeg to verify successful local execution and output generation.
    """
    # 1. Create a temp directory for test assets
    temp_dir = tempfile.mkdtemp()
    input_path = os.path.join(temp_dir, "input.mp4")
    output_dir = os.path.join(temp_dir, "output")
    video_id = "test-integration-uuid"

    try:
        # 2. Generate a valid 6-second dummy video using local FFmpeg
        # (It must be at least 5 seconds long since we capture a thumbnail at 5s mark)
        gen_cmd = [
            "ffmpeg", "-y", "-f", "lavfi", "-i", "testsrc=duration=6:size=320x240:rate=25",
            "-pix_fmt", "yuv420p", input_path
        ]
        res = subprocess.run(gen_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        assert res.returncode == 0, f"Failed to generate test dummy video: {res.stderr.decode()}"

        # 3. Invoke transcode_video
        success = transcode_video(input_path, output_dir, video_id)
        assert success is True

        # 4. Verify outputs are generated, exist, and are non-empty
        output_720p = os.path.join(output_dir, f"{video_id}_720p.mp4")
        output_480p = os.path.join(output_dir, f"{video_id}_480p.mp4")
        thumbnail_path = os.path.join(output_dir, f"{video_id}_thumbnail.png")

        assert os.path.exists(output_720p)
        assert os.path.getsize(output_720p) > 0

        assert os.path.exists(output_480p)
        assert os.path.getsize(output_480p) > 0

        assert os.path.exists(thumbnail_path)
        assert os.path.getsize(thumbnail_path) > 0

    finally:
        # Clean up
        shutil.rmtree(temp_dir)


def test_transcode_video_missing_file():
    """
    Verify that transcode_video gracefully handles cases where the input file is missing.
    """
    success = transcode_video("non_existent_file.mp4", "some_output_dir", "some_uuid")
    assert success is False
