# Generated by Django 5.2.16 on 2026-07-15 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_number', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.TextField()),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='parser.document')),
            ],
        ),
        migrations.CreateModel(
            name='RiskFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to='parser.extractedclause')),
            ],
        ),
    ]
