# Generated by Django 5.2.16 on 2026-07-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_document_content_hash_document_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedclause',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extractedclause',
            name='jurisdiction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
